### PR TITLE
FIX: one last time to provide individual maps for the CNN

### PR DESCRIPTION
**Pull request by azabicki**

### CODE REVIEW

**Review by eockfen — APPROVED** [review]
good job! :))

**Comment by azabicki** [comment]
sorry elena, I added another commit to my branch before merging it, so an new approval is needed...

**Review by MSantoro87 — DISMISSED** [review]
Thanks again for it! 😀

**Comment by azabicki** [comment]
OK I am something new here: it seems that Marian's approval is not sufficient. I guess elena needs to approve because she originaly approved the pr before further changes were commited...

**Comment by MSantoro87** [comment]
One of the take-home message coming out of our experience in this bootcamp: "If you are tired of GitHub, you are tired of the life". 😀🤣

**Review by eockfen — DISMISSED** [review]

**Comment by azabicki** [comment]
wondering why it still is blocked...

@CrazyTrain93 @DDombrovskij could you please approve

**Review by DDombrovskij — DISMISSED** [review]

**Comment by CrazyTrain93** [comment]
test - looks good

**Review by CrazyTrain93 — DISMISSED** [review]
ok

**Review by eockfen — APPROVED** [review]

**Pull request merged**
